---
title: "Uzd2_Sakele"
author: "Vita"
date: "2024-12-15"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Lejupielāde
```{r cache=TRUE, warning=FALSE, message=FALSE}
if (!require("RCurl")) install.packages("RCurl");library(RCurl)
if (!require("archive")) install.packages("archive");library(archive)

if (!dir.exists("download")) {
  dir.create("download")
}


url= "https://data.gov.lv/dati/lv/dataset/40014c0a-90f5-42be-afb2-fe3c4b8adf92/resource/392dfb67-eeeb-43c2-b082-35f9cf986128/download/centra.7z"

destfile = "Download/centra.7z"

download.file(url=url, destfile = destfile, mode='wb')



if (!dir.exists("data")) {
  dir.create("data")
}
archive_extract(destfile, dir = "data")


```

#Konvertācija un izmēri

```{r cache=TRUE, warning=FALSE, message=FALSE}
if (!require("sf")) install.packages("sf")
library(sf)


if (!dir.exists("converted_data")) {
  dir.create("converted_data")
}

# Path to your shapefile
shapefile_path <- "data/nodala2651.shp" 

# Read the shapefile into an sf object
shp <- st_read(shapefile_path)

# Convert to GeoPackage
st_write(shp, "converted_data/output.gpkg", driver = "GPKG")

# Convert to GeoParquet
if (!require("sfarrow")) install.packages("sfarrow")
library(sfarrow)
st_write_parquet(shp, "converted_data/output.parquet")
```

```{r cache=TRUE, warning=FALSE}
file.size("converted_data/output.parquet") # 21 795 679
file.size("converted_data/output.gpkg") # 57 188 352
file.size("data/nodala2651.shp") #27 090 844 + pārējie ar slāni saistītie faili

rm(shp)
```

#Ielasīšanas laika mērījumi
```{r}
if (!require("microbenchmark")) install.packages("microbenchmark")
library(microbenchmark)
```

```{r cache = TRUE}
ielades_atrums <- microbenchmark(
  read_shape = st_read("data/nodala2651.shp"), # vidēji 9.6 sek
  read_gpkg = st_read("converted_data/output.gpkg"), # vidēji 6.5 sek
  read_parquet = st_read_parquet("converted_data/output.parquet"), #vidēji 2.5 sek
  times = 10,
  unit="s"
)
print(ielades_atrums)
```


#Failu apvienošana

```{r cache=TRUE}
if (!dir.exists("data/combined")) {
  dir.create("data/combined")
}

file_list <- list.files("data", pattern = "*shp$", full.names = TRUE)
shapefile_list <- lapply(file_list, read_sf) #ielasa visus failus
combined_shapefile <- do.call(rbind, shapefile_list) # apvieno vienā failā
st_write(combined_shapefile, "data/combined/centra.gpkg", driver = "GPKG")

rm(combined_shapefile, shapefile_list)
```

#Ģeometriju pārbaude
```{r cache=TRUE}
centra_gpkg <- st_read("data/combined/centra.gpkg")

# Pārbaudīt, vai visas ģeometrijas ir MULTIPOLYGON
if(all(st_geometry_type(centra_gpkg) == "MULTIPOLYGON")) {
  print("Visas ģeometrijas ir MULTIPOLYGON")
} else {
  print("Dažas ģeometrijas nav MULTIPOLYGON")
  }

# Pārbaudīt, vai nav tukšu ģeometriju
if(any(st_is_empty(centra_gpkg))) {
  print("Slānī ir tukšas ģeometrijas")
  # Izdzēst tukšās ģeometrijas
  centra_gpkg <- centra_gpkg[!st_is_empty(centra_gpkg), ] 
}

# Pārbaudīt, vai nav kļūdainu ģeometriju
if(any(!st_is_valid(centra_gpkg))) {
  print("Slānī ir kļūdainas ģeometrijas")
 # Salabot ķļūdainās ģeomtrijas
  centra_gpkg <- st_make_valid(centra_gpkg)
  # Izdzēst kļūdainās ģeometrijas
  centra_gpkg <- centra_gpkg[st_is_valid(centra_gpkg), ] 
}

```


#Priežu meži

```{r}
# Ģeometrijas vairs nav vajadzīgas, var izmanto arī parquet failu
centra_df<-data.frame(centra_gpkg)
rm(centra_gpkg)
```

```{r cache=TRUE}
if (!require("dplyr")) install.packages("dplyr")
library(dplyr)

pine_codes = c(1, 14, 22)
centra_df <- centra_df %>%
 mutate(
   pine_basal_area = (
      ifelse(s10 %in% pine_codes, g10, 0) +
        ifelse(s11 %in% pine_codes, g11, 0) +
        ifelse(s12 %in% pine_codes, g12, 0) +
        ifelse(s13 %in% pine_codes, g13, 0) +
        ifelse(s14 %in% pine_codes, g14, 0)),
     
  total_basal_area = g10+g11+g12+g13+g14,
  prop_priede = pine_basal_area/total_basal_area,
  PriezuMezi = ifelse(is.nan(prop_priede), 0, 
               ifelse(prop_priede >= 0.75, 1, 0)) 
  )

centra_df$pine_basal_area<-NULL

#Priežu meži no visiem mežiem mežaudze (zkat=="10")
sum(centra_df$PriezuMezi)/nrow(centra_df[centra_df$zkat == "10", ])


```
#Citi  meži

Ja sugas, kas pieder konkrētam meža tipam, veido vismaz 75% šķērslaukuma, tad 
tiek izskatīts, ka mežs ir attiecigā tipa. Pretējā gadījumā tas ir jauktu koku mežs, jo
neviena sugu grupa nedominē.

```{r cache=TRUE}
#Sugu piederība
conifers_codes = c(1, 3, 13, 14, 15, 22, 23, 28, 29)
broadleaves_codes = c( 10, 11, 12, 16, 17, 18, 19, 20, 21, 24, 25, 26, 27, 32, 35, 50, 61, 62, 63, 64, 65, 66, 67, 69)
narrowleaves_codes = c(4, 6, 8, 9, 68)

# vispār te vajadzētu funkciju
centra_df <- centra_df%>%
  filter(zkat=='10') %>% #tikai mežaudzes
  mutate(
    conifers_basal_area = 
      (s10 %in% conifers_codes * g10) + 
      (s11 %in% conifers_codes * g11) + 
      (s12 %in% conifers_codes * g12) + 
      (s13 %in% conifers_codes * g13) + 
      (s14 %in% conifers_codes * g14),
    broadleaves_basal_area = 
      (s10 %in% broadleaves_codes * g10) + 
      (s11 %in% broadleaves_codes * g11) + 
      (s12 %in% broadleaves_codes * g12) + 
      (s13 %in% broadleaves_codes * g13) + 
      (s14 %in% broadleaves_codes * g14),
    narrowleaves_basal_area = 
      (s10 %in% narrowleaves_codes * g10) + 
      (s11 %in% narrowleaves_codes * g11) + 
      (s12 %in% narrowleaves_codes * g12) + 
      (s13 %in% narrowleaves_codes * g13) + 
      (s14 %in% narrowleaves_codes * g14),
    forest_type=
      case_when(
      narrowleaves_basal_area / total_basal_area >= 0.75 ~ "Šaurlapju mežs",
      broadleaves_basal_area / total_basal_area >= 0.75 ~ "Platlapju mežs",
      conifers_basal_area / total_basal_area >= 0.75 ~ "Skujkoku mežs",
      TRUE ~ "Jauktu koku mežs")
  )


```

```{r}
nrows=nrow(centra_df)
forest_ratios<-centra_df %>%
  group_by(forest_type) %>%
  summarize(ratio = n() / nrows) 

forest_ratios
```


#Visu mežaudžu failu dzēšana
```{r}

unlink("data", recursive = TRUE)
unlink("converted_data", recursive = TRUE)
unlink("download", recursive = TRUE)

rm(centra_df)
```


